### ISSUE TITLE
Dummy oauth-secrets.json file?

### ISSUE THREAD

**Issue by megacoder** [benreic/fsync#13]
To avoid the effort of reverse-engineering the oauth-secrets.json file you are expecting, could you provide a sample file?

**Comment by benreic** [comment]
Yep, see attached text file. All the values in the file should be provided to you from Flickr I believe, but its been awhile since I set this part of it up.

[sample-oauth-secrets.json.txt](https://github.com/benreic/fsync/files/966497/sample-oauth-secrets.json.txt)

**Comment by megacoder** [comment]
Thank you, I'll give it a try.
